Init tool
biopet/extractadaptersfastqc pull request #1
Opened 2018-01-11 09:56 UTC by ffinfo

2018-01-11 14:13 UTC, rhpvorderman requested changes
Great! Just some textual comments.

2018-01-11 14:13 UTC, rhpvorderman commented on LICENSE
> +Copyright (c) 2017 Biopet
Since this code was part of flexiprep the correct year should be 2014. It is not allowed to give a later year if versions of the code with an earlier year can be found.

Can you modify the startYear in `build.sbt` accordingly?

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +    .text("Output file for adapters, is not supplied output will go to stdout")
if* not supplied

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +    .text("Output file for adapters, is not supplied output will go to stdout")
idem

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +      "If this is set only the adapters block is used, other wise contamination is also used")
otherwise

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +      "This is the file that does contain the known contamination from fastqc")
is this contamination**s** ?

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +      "This is the file that does contain the known contamination from fastqc")
Also `This is` is redundant here.

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +    .text("This is the file that does contain the known adapters from fastqc")
`This is` is redundant

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ExtractAdaptersFastqc.scala
> +      | The output can be only sequences or in a fasta format.
The sequences can be output in plain text format with a newline character as a separator between the sequences. Alternatively the sequences can be output in FASTA format.

2018-01-11 14:13 UTC, rhpvorderman commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ExtractAdaptersFastqc.scala
> +      |This files are required for this tool to find the correct adapters.
These files

2018-01-11 15:03 UTC, hailiangmei commented on src/main/scala/nl/biopet/tools/extractadaptersfastqc/ArgsParser.scala
> +    .text("Output file for adapters, is not supplied output will go to stdout")
Fastqc data file -> Fastqc data file (i.e., fastqc_data.txt file in the FastQC output).

Output file for adapters, is not supplied output will go to stdout -> Output file contains detected list of adapters by FastQC based on the specified cutoff value

2018-01-11 15:08 UTC, hailiangmei commented
Should we make options like adapterFile, contamFile required? To prevent users make mistake that they miss adapter sequences that should be reported by this tool? 
And I wonder if we should merge adapterOutputFile and contamsOutputFile into one file here as the output of this tool.

2018-01-12 09:45 UTC, ffinfo commented
Making those files required is hard because not all versions of fastqc have this files. What I did for now is to check if if there are known sequences in 1 of the 2 files. If 0 it will raise an exception.

2018-01-12 09:48 UTC, ffinfo commented
@rhpvorderman: can you recheck this?

2018-01-15 11:51 UTC, rhpvorderman approved these changes

2018-01-15 11:52 UTC, merged